다이어리 CRUD 구현
PoolC/Javaccino pull request #5
Opened 2021-08-27 06:40 UTC by Bucket1572

성급하게 Push했습니다. 그렇다고 force push로 되돌리기도 좀 그래서... 아직 완성된 것이 아니고, 완성 후에 이 PR에 다시 push할 테니, merge하지 말아주세요.

2021-09-07 13:37 UTC, Bucket1572 commented
> 제가 현직자에게 들은 피드백을 인용하면, uri에 id가 아닌 nickname과 같은 user 파라미터를 넘겨받는 경우(user crud)는 {nickname}앞에 user/를 붙이는 것이 더 자연스럽다고 합니다. 제가 담당한 방명록 부분을 예시로 보여드리면
> 
> 방명록 전체 조회: GET /guestbooks/{nickname} -> /guestbooks/user/{nickname}
> (혹시 방명록 단일 조회가 생기면 GET /guestbooks/{guestbookId} 로 쓸수있음)
> 방명록 작성: POST /guestbooks/{nickname} -> /guestbooks/user/{nickname}
> 방명록 수정: PUT /guestbooks/{guestbookId}
> 방명록 신고: POST /guestbooks/report/{guestbookId}
> 방명록 삭제: DELETE /guestbooks/{guestbookId}
> 방명록 전체 삭제: DELETE /guestbooks/{nickname} -> /guestbooks/user/{nickname}
> 방명록 숨기기: POST /guestbooks/blind/{guestbookId}
> 
> 와 같이 수정하였습니다. 저도 현재 다이어리와 비슷한 부분을 담당하고 있고, 이에 관련해서 현직자에게 들은 조언을 전해드리는 것이 좋을 것 같아서 남깁니다!

넵 알겠습니다. 해당 방식을 적용하도록 하겠습니다.

2021-09-24 08:50 UTC, Bucket1572 commented
마지막 테스트 수정은

1. diaryDataLoader을 잘 구성해서 기존 memberDataLoader에 종속적이던 것을 독립적인 것으로 바꿨습니다.
2. @Transactional 추가로 기존 서로 의존적이던 테스트 메소드들을 독립적인 것으로 바꿨습니다.

#### 기대되는 바
- 테스트가 독립적이므로, 실행 순서가 딱히 중요하지 않을 것입니다.
- UUID 추가 등의 테스트 코드 수정이 필요한 상황에서 큰 영향을 받지 않을 것입니다.
- 원하는 메소드만 선택하여 실행할 수 있을 것입니다. (이건 확인했습니다.)

2021-09-24 08:51 UTC, Bucket1572 commented
감정 점수 Entity만 후딱 작성, review 요청하고 끝나면 바로 이 thread를 review 요청하겠습니다.

2021-09-30 13:39 UTC, hcpak requested changes
@Bucket1572 님 수고하셨어요! emotionScore 쪽 로직 짜시느라 고생 많이하셨습니다. emotionScore 로직 어떻게 짜셨는지 나중에 설명해주시면 감사하겠습니다.

2021-09-30 13:39 UTC, hcpak commented on src/main/java/com/emotie/api/common/domain/Postings.java
> +    protected Member writer;
연관관계를 맺을 때 EAGER 방식으로 불러오는 것보다 일단 LAZY 방식으로 불러오고 필요할 때 EAGER 바꾸는 게 좋아보입니다!

2021-09-30 13:39 UTC, hcpak commented on src/main/java/com/emotie/api/diary/controller/DiaryController.java
> +        String updatingEmotion = diaryUpdateRequest.getEmotion();
뭔가 DTO로 getEmotion() 하니까 어색하네요. memberService.updateEmotionScore() 파라미터에 dto를 넘겨주는 방식이 좀 더 깔끔한 거 같은데 어떻게 생각하시나요?

2021-09-30 13:39 UTC, hcpak commented on src/main/java/com/emotie/api/diary/controller/DiaryController.java
> +                }
it가 iterator인지 알겠지만 diary가 좀 더 명시적이라 좋을 거 같습니다.

2021-09-30 13:39 UTC, hcpak commented on src/main/java/com/emotie/api/diary/controller/DiaryController.java
> +    }
이 곳은 아직 로직이 완성되지 않은 부분인가요?

2021-09-30 13:39 UTC, hcpak commented on src/main/java/com/emotie/api/diary/domain/Diary.java
> +    private LocalDate issuedDate;
프론트 엔드 분들과 이것에 대해서 얘기해봤는데, 해당 감정을 느낀 즉시 글을 작성하는 것이기 때문에 작성할 일기 날짜를 정할 필요가 없다고 하네요!

2021-09-30 13:39 UTC, hcpak commented on src/main/java/com/emotie/api/diary/dto/DiaryDeleteRequest.java
> +}
id만 받을 거면 Request 파라미터로 받거나, query string으로 받는 게 나을 거 같은데, 이렇게 해도 상관은 없을 거 같습니다.

2021-09-30 13:39 UTC, hcpak commented on src/main/java/com/emotie/api/diary/repository/DiaryRepository.java
>  //    List<Diaries> findBeforeDate(Date endDate);
사용하지 않는 메소드는 주석처리가 아니라 없애주시면 감사하겠습니다!

2021-09-30 13:39 UTC, hcpak commented on src/main/java/com/emotie/api/diary/service/DiaryService.java
> +@SuppressWarnings("unused")
이건 어떤 역할을 하는 건가요??

2021-09-30 13:39 UTC, hcpak commented on src/main/java/com/emotie/api/diary/service/DiaryService.java
> +        checkIsOpened(user, diary);
이 부분은 diary 도메인 메소드로 하는 것이 더 좋아보입니다.

2021-09-30 13:39 UTC, hcpak commented on src/main/java/com/emotie/api/diary/service/DiaryService.java
> +        updateDiaryWithRequest(diary, request);
이 부분 한 컬럼, 한 컬럼씩 수정하는 방식으로 동작하는데, diary.update(request)로 한번에 처리하는 건 어떻게 생각하시나요?

2021-09-30 13:39 UTC, hcpak commented on src/main/java/com/emotie/api/diary/service/DiaryService.java
> +        checkUpdateRequestValidity(user, request, diary);
파라미터가 3개나 되는 경우는 최대한 없애야 합니다. 따라서 메소드를 2개로 만드는 방식으로 하면 어떻게 생각하시나요?
또한 validity를 검증할 때는 도메인측에서 하는 것이 좋아보입니다. 예를 들어 request가 제대로 왔는지 확인하려면 request.checkValidity() 이런 식으로 하는 게 좋아보이네요.

2021-09-30 13:39 UTC, hcpak commented on src/main/java/com/emotie/api/diary/service/DiaryService.java
> +                    emotionRepository.saveAndFlush(diary.getEmotion());
뭔가 null exception이 터질 거 같은 로직이네요. 근데 emotion에 왜 diariesList가 존재하나요? emotion에 diaryList가 존재할 필요는 없을 거 같습니다. 왠만해서 양방향 연관관계는 지양하는 게 좋아보입니다. 또한 diaryList는 mappedby로 되어 있어서 DB상으로 쿼리가 날라갈 일이 없으니 emotionRepository.saveAndFlush(diary.getEmotion()); 할 필요 없을 거 같습니다.

2021-09-30 13:39 UTC, hcpak commented on src/main/java/com/emotie/api/diary/service/DiaryService.java
> +    }
해당 로직은 도메인 메소드로 대체 가능할 거 같아요

2021-09-30 13:39 UTC, hcpak commented on src/main/java/com/emotie/api/emotion/domain/Emotion.java
> +    private List<Diary> diariesList = new ArrayList<>();
이 컬럼은 개인적으로 필요 없을 거 같은데 diariesList가 필요한 경우가 있나요?

2021-09-30 15:05 UTC, Bucket1572 commented on src/main/java/com/emotie/api/common/domain/Postings.java
> +    protected Member writer;
연관 관계 매핑이 emotionScore 쪽에 필요없어서, ManyToOne은 빼고, writer_id만 저장하는 것으로 바꾸었습니다.

2021-09-30 16:48 UTC, Bucket1572 commented on src/main/java/com/emotie/api/diary/controller/DiaryController.java
> +    }
네 지금은 CRUD만 구현했습니다.

2021-09-30 16:51 UTC, Bucket1572 commented on src/main/java/com/emotie/api/emotion/domain/Emotion.java
> +    private List<Diary> diariesList = new ArrayList<>();
이 부분에 대해서는 저보다는 연웅님이 잘 아실 것 같습니다. @AceSuited 

다만, 제가 그때 연웅님과 함께 merge할 때, 이모션에서 이 리스트를 썼던 것 같습니다.

2021-09-30 16:55 UTC, Bucket1572 commented on src/main/java/com/emotie/api/diary/controller/DiaryController.java
> +        String updatingEmotion = diaryUpdateRequest.getEmotion();
좋은 방식인 것 같긴 한데, 파라미터 사이의 대칭성을 부여하고 싶었습니다. 두 조건을 동시에 성립하게 하는 방법이 있을까요?

2021-09-30 16:55 UTC, Bucket1572 commented on src/main/java/com/emotie/api/diary/controller/DiaryController.java
> +                }
네 알겠습니다. 사실은 그냥 대명사로 it을 쓴 것이긴 한데;;

2021-09-30 16:56 UTC, Bucket1572 commented on src/main/java/com/emotie/api/diary/domain/Diary.java
> +    private LocalDate issuedDate;
그렇다고 하더라도 DB 상에는 저장하고 있어야 하는 거 아닌가요? 그러면, 일기 날짜는 기억하지 않는 걸로???

2021-09-30 16:57 UTC, Bucket1572 commented on src/main/java/com/emotie/api/diary/service/DiaryService.java
> +        updateDiaryWithRequest(diary, request);
잘 이해하지 못했습니다. 이에 대해서는 따로 이야기 해 보아야 할 것 같습니다.

2021-09-30 16:59 UTC, Bucket1572 commented on src/main/java/com/emotie/api/diary/service/DiaryService.java
> +                    emotionRepository.saveAndFlush(diary.getEmotion());
양방향 연관 관계 부분에 대해서는 이번 회의 때 다시 여쭤보기로 하겠습니다.

2021-09-30 17:18 UTC, Bucket1572 commented on src/main/java/com/emotie/api/diary/controller/DiaryController.java
> +                }
수정하여 push 했습니다.

2021-09-30 22:14 UTC, hcpak commented on src/main/java/com/emotie/api/diary/domain/Diary.java
> +    private LocalDate issuedDate;
넵넵 일기 날짜는 createdDate를 통해 가져오는 걸로 생각하시면 될 거 같습니다!

2021-09-30 22:39 UTC, hcpak commented on src/main/java/com/emotie/api/diary/controller/DiaryController.java
> +        String updatingEmotion = diaryUpdateRequest.getEmotion();
음... 지금 originalEmotion과 updateEmotion에 대해 알아야지만 memberSevice.updateEmotionScore()를 사용할 수 있다는 것이라 diaryService.update하는 로직안에다가 memberSevice.updateEmotionScore() 사용하면 어떨까라는 생각은 들긴 들었습니다만, 좋은 방법인지는 확신이 안드네요.

2021-09-30 22:42 UTC, hcpak approved these changes
수고하셨습니다!

2021-10-01 05:54 UTC, powerkim417 commented on src/main/java/com/emotie/api/common/domain/Postings.java
> +    protected Member writer;
저는 Postings에 writer ManyToOne으로 달고 쓰고 있는데, ManyToOne을 빼면 작성자 uuid만 남아서 다이어리와 함께 작성자와 관련된 정보를 같이 띄우려면 작성자 uuid로 작성자를 검색하는 쿼리를 한번 더 사용해야 하는 것 아닌가요?? emotionScore가 writer의 연관관계 매핑과 어떤 관련이 있는건지 잘 이해하지 못했습니다.

2021-10-01 06:03 UTC, powerkim417 commented on src/main/java/com/emotie/api/member/domain/EmotionScore.java
> +        if (this.count <= 0) throw new IndexOutOfBoundsException("글의 개수가 음수가 될 수는 없습니다.");
제가 잘 몰라서 그런데 count가 인덱스가 아닌 상황에서 IndexOutOfBoundsException을 쓰는 것이 적합한지 잘 모르겠네요.

2021-10-01 06:03 UTC, Bucket1572 commented on src/main/java/com/emotie/api/common/domain/Postings.java
> +    protected Member writer;
아 emotionScores 쪽이 아니라 Postings 쪽이네요 수정하겠습니다

2021-10-01 07:05 UTC, Bucket1572 commented on src/main/java/com/emotie/api/emotion/domain/Emotion.java
> +    private List<Diary> diariesList = new ArrayList<>();
없애는 것으로 결정했습니다. Resolve 하겠습니다.

2021-10-01 07:07 UTC, Bucket1572 commented on src/main/java/com/emotie/api/diary/service/DiaryService.java
> +@SuppressWarnings("unused")
surpresswarnings는 intelliJ에서 해당 사항에 대해 주의를 표하지 않게 만드는 어노테이션입니다. intellij를 위한 주석이라 보아도 무관한데, 개발 중에 관계 없는 warning을 없애기 위해 추가했습니다.

2021-10-03 11:25 UTC, Bucket1572 commented on src/main/java/com/emotie/api/diary/controller/DiaryController.java
> +    }
일단 이 부분은 이후 다른 pr에서 다룰 예정이므로, resolve하겠습니다.

2021-10-03 11:25 UTC, Bucket1572 commented on src/main/java/com/emotie/api/common/domain/Postings.java
> +    protected Member writer;
Eager에서 LAZY로 수정되었습니다.

2021-10-04 02:37 UTC, Bucket1572 commented on src/main/java/com/emotie/api/diary/domain/Diary.java
> +    private LocalDate issuedDate;
issuedDate는 지웠고, DTO에서는 createdAt을 ISODATE 포맷으로 보내는 것으로 바꾸었습니다.

2021-10-04 02:38 UTC, Bucket1572 commented on src/main/java/com/emotie/api/diary/domain/Diary.java
> +    private LocalDate issuedDate;
resolve하겠습니다.

2021-10-04 02:38 UTC, Bucket1572 commented on src/main/java/com/emotie/api/diary/dto/DiaryDeleteRequest.java
> +}
넵. 사실 Request 파라미터로 받는게 조금 더 괜찮아 보이기는 하는데, 이왕 이렇게 구현한 거, 그냥 놔두겠습니다.

2021-10-04 02:48 UTC, Bucket1572 commented on src/main/java/com/emotie/api/diary/service/DiaryService.java
> +                    emotionRepository.saveAndFlush(diary.getEmotion());
양방향 연관 관계는 저번 회의 이후 없어진 것으로 알고 있습니다.

2021-10-04 02:49 UTC, Bucket1572 commented on src/main/java/com/emotie/api/diary/service/DiaryService.java
> +        checkIsOpened(user, diary);
도메인 메소드로 수정했습니다. 곧 push할 예정입니다.

2021-10-04 02:51 UTC, Bucket1572 commented on src/main/java/com/emotie/api/diary/service/DiaryService.java
> +        updateDiaryWithRequest(diary, request);
아 update(request)의 경우, 감정을 현재 알 수 있는 방법이 없어서 불가능해 보입니다. 감정은 repository에 직접 접근해야만 받아올 수 있습니다. 다만, 여러 params를 넘겨주는 방식으로 구현하는 것은 가능해 보입니다.

2021-10-04 02:51 UTC, Bucket1572 commented on src/main/java/com/emotie/api/diary/service/DiaryService.java
> +        updateDiaryWithRequest(diary, request);
그래서 일단은 현재와 같은 상태로 놔두겠습니다. 추후, 수정이 필요할 경우 다시 말씀해 주세요.

2021-10-04 02:55 UTC, Bucket1572 commented on src/main/java/com/emotie/api/diary/service/DiaryService.java
> +        checkUpdateRequestValidity(user, request, diary);
일단은 DTO가 아니라 diary 도메인 쪽으로 검증 로직을 뺐습니다. 사용자에 대한 검증이 필요하기 때문에, request 자체에서는 검증하기 어렵게 보입니다. Controller에서 구현하려고 해도, 이번에는 다이어리에 대한 정보가 없기 때문에 쉽지 않습니다. 결국은 diary 자체 혹은 service에서만 구현 가능해 보입니다.

2021-10-04 02:57 UTC, Bucket1572 commented on src/main/java/com/emotie/api/diary/service/DiaryService.java
> +    }
일단은 최대한 service에서 해당 로직들을 뺐습니다만, 일부는 user에 대한 정보나 diary에 대한 정보가 필요하여 다이어리 도메인으로 빠지거나, 서비스에 남을 수밖에 없었습니다.

2021-10-04 03:05 UTC, Bucket1572 commented on src/main/java/com/emotie/api/member/domain/EmotionScore.java
> +        if (this.count <= 0) throw new IndexOutOfBoundsException("글의 개수가 음수가 될 수는 없습니다.");
ArithmeticException으로 수정했습니다. 산술 조건을 만족하지 못했다는 느낌으로 수정했는데, 너무 넓은 단위를 잡은 것은 아닐지 의문이 들긴 합니다.

2021-10-04 03:05 UTC, Bucket1572 commented on src/main/java/com/emotie/api/diary/repository/DiaryRepository.java
>  //    List<Diaries> findBeforeDate(Date endDate);
네 알겠습니다.

2021-10-04 03:07 UTC, Bucket1572 commented on src/main/java/com/emotie/api/diary/controller/DiaryController.java
> +        String updatingEmotion = diaryUpdateRequest.getEmotion();
diaryService 안에서 memberService를 가져와도 되나요?

2021-10-04 03:14 UTC, Bucket1572 commented
일단은 review도 대부분 해결하고, 문제도 없어 보입니다. 추가적인 논의가 없다면 merge해도 될 것 같습니다.

2021-10-04 13:07 UTC, hcpak commented on src/main/java/com/emotie/api/diary/controller/DiaryController.java
> +        String updatingEmotion = diaryUpdateRequest.getEmotion();
순환 참조 문제가 발생할 수 있다는 생각이 들어서 좋은 생각 같기도 나쁜 생각인 거 같기도 하는 생각이 드네요....

2021-10-04 13:10 UTC, hcpak approved these changes
수고하셨어요!

2021-10-04 16:11 UTC, powerkim417 commented on src/main/java/com/emotie/api/member/domain/EmotionScore.java
> +        if (this.count <= 0) throw new IndexOutOfBoundsException("글의 개수가 음수가 될 수는 없습니다.");
그러게요.. 저도 좀 아쉬운 면이 있는데 찾아봐도 딱 맞는 예외가 없네요.. 아니면 저희가 따로 만드는 건 어떻게 생각하세요??

2021-10-05 10:32 UTC, Bucket1572 commented on src/main/java/com/emotie/api/member/domain/EmotionScore.java
> +        if (this.count <= 0) throw new IndexOutOfBoundsException("글의 개수가 음수가 될 수는 없습니다.");
그냥 Arithmetic Exception 써도 될 것 같습니다. 새로 만들어도 되기는 하지만, 그냥 계산 오류가 있으면 다 산술 오류로 해도 될 거 같은 생각이 듭니다.

2021-10-05 10:36 UTC, merged

2021-10-05 10:37 UTC, powerkim417 commented on src/main/java/com/emotie/api/member/domain/EmotionScore.java
> +        if (this.count <= 0) throw new IndexOutOfBoundsException("글의 개수가 음수가 될 수는 없습니다.");
넵 알겠습니다!