방명록 테스트 코드 및 서비스 추가
PoolC/Javaccino pull request #6
Opened 2021-08-27 09:52 UTC by powerkim417

2021-09-30 14:15 UTC, hcpak requested changes
@powerkim417 님 수고 많이하셨습니다!

2021-09-30 14:15 UTC, hcpak commented on src/main/java/com/emotie/api/guestbook/service/GuestbookService.java
> +    }
checkGuestbookIdExists와 checkNotOverReported는 같이 검사할 수 있을 거 같습니다. 또한 checkWriter(user, guestbookId)는 user.checkWriter(guestbook)으로 체크할 수 있을 거 같습니다. 저는 다음과 같이 로직을 짤 거 같습니다.
```
Guestbook guestbook = getGuestbookById(guestbookId);
guestbook.checkNotverReported();
user.checkWriter(guestbook);
```

2021-09-30 14:15 UTC, hcpak commented on src/main/java/com/emotie/api/guestbook/service/GuestbookService.java
> +     */
주석은 최대한 없애주시는 것이 좋을 거 같습니다.

2021-09-30 14:15 UTC, hcpak commented on src/main/java/com/emotie/api/guestbook/service/GuestbookService.java
> +    }
해당 로직들도 위에 있는 것과 같이 리펙토링 가능할 거 같습니다. 그리고 validity 검증하는 로직은 도메인(엔티티)에 존재하는 것이 좋을 거 같습니다.

2021-09-30 14:15 UTC, hcpak commented on src/main/java/com/emotie/api/guestbook/service/GuestbookService.java
> +    }
오버로딩을 하신 거 같은데 저는 개인적으로 메소드명을 달리하는 것이 좀 더 좋아보이긴 하는데 이거는 제 개인적인 견해입니다.

2021-09-30 14:15 UTC, hcpak commented on src/main/java/com/emotie/api/guestbook/service/GuestbookService.java
> +        if (!(user.equals(guestbook.getWriter()) || user.equals(guestbook.getOwner()))) {
음 저라면 if(guestbook.checkWriter(user) || guestbook.checkOwner(user)) 이런 방식으로 검증했을 거 같습니다. get을 쓰면 왠지 널포인터 exception이 발생할 거 같아요.

2021-09-30 14:15 UTC, hcpak commented on src/main/java/com/emotie/api/guestbook/domain/Guestbook.java
> +@Getter
저번 주에 @Jjungs7  인터페이스 강의를 들었기 때문에 Getter를 모두 지우는 것이 좋아보이네요.

2021-09-30 14:15 UTC, hcpak commented on src/main/java/com/emotie/api/member/domain/Member.java
> +    // TODO: reference object의 경우 one to many로 연결하는게 더 좋다는데..
이거는 왜 그런 건가요?

2021-09-30 14:15 UTC, hcpak commented on src/main/java/com/emotie/api/member/domain/Member.java
> +    }
report가 음수가 될리 없겠지만 방지하는 로직이 필요할 거 같습니다.

2021-09-30 14:15 UTC, hcpak commented on src/main/java/com/emotie/api/member/service/MemberService.java
>                      throw new UnauthenticatedException("로그인하지 않았습니다.");
해당 로직은 auth에 있는 webSecurityFilter에서 검증하므로 필요없는 로직일 거 같습니다.

2021-09-30 14:39 UTC, powerkim417 commented on src/main/java/com/emotie/api/common/domain/Postings.java
>      protected Integer id;
넵 방명록 id 모두 Long으로 수정했습니다!

2021-09-30 14:44 UTC, powerkim417 commented on src/main/java/com/emotie/api/common/exceptionHandler/CommonExceptionHandlers.java
> +            CannotFollowException.class, MyselfException.class
자신의 방명록에 글을 쓰려고 하는 경우나, 자신이 작성한 방명록 글을 신고하려는 경우처럼 자기 자신에게 하게 될 동작이 금지된 경우에 대한 exception을 모아보고자 만들었습니다.

2021-09-30 14:45 UTC, powerkim417 commented on src/main/java/com/emotie/api/guestbook/controller/GuestbookController.java
> +//                .filter(guestbook -> guestbook.isNotOverReported() && !guestbook.getIsGlobalBlinded())
넵 지우겠습니다!

2021-09-30 14:57 UTC, powerkim417 commented on src/main/java/com/emotie/api/guestbook/service/GuestbookService.java
> +        checkGetAllBoardsRequestValidity(user, nickname);
엇 그러면 모든 check~~RequestValidity에서 CheckLogin을 다 빼면 될까요??

2021-09-30 14:58 UTC, powerkim417 commented on src/main/java/com/emotie/api/guestbook/service/GuestbookService.java
> +        checkGetAllBoardsRequestValidity(user, nickname);
혹시 그러면 memberService에서 검증할 때 들어가는 checkLogin도 다 필요 없는건가요?!

2021-09-30 15:19 UTC, powerkim417 commented on src/main/java/com/emotie/api/guestbook/service/GuestbookService.java
> +        return guestbookRepository.findForUserByOwner(owner, Guestbook.reportCountThreshold);
예쁘게 짠다는 것이 분기 없이 user를 쿼리에 전달하고 쿼리단에서 분기하는 쪽으로 생각하고 계시는건가요??

2021-09-30 15:59 UTC, hcpak commented on src/main/java/com/emotie/api/common/domain/Postings.java
> +    protected Member writer;
모두 같이 띄우게 된다면 EAGER가 맞는 거 같습니다!

2021-09-30 15:59 UTC, hcpak commented on src/main/java/com/emotie/api/guestbook/controller/GuestbookController.java
> +    }
음 그런게 아니라 body에다가 guestbookid를 넣으라는 건데 굳이 그렇게 안하셔도 될거 같아요!

2021-09-30 16:03 UTC, powerkim417 commented on src/main/java/com/emotie/api/guestbook/service/GuestbookService.java
> +     */
넵 알겠습니다

2021-09-30 16:03 UTC, powerkim417 commented on src/main/java/com/emotie/api/guestbook/service/GuestbookService.java
> +    }
넵 각 도메인에서 할 수 있는 메서드들은 각 메서드 내에 옮기겠습니다.

2021-09-30 16:37 UTC, AceSuited commented on src/main/java/com/emotie/api/guestbook/service/GuestbookService.java
> +        checkGetAllBoardsRequestValidity(user, nickname);
> 혹시 그러면 memberService에서 검증할 때 들어가는 checkLogin도 다 필요 없는건가요?!

그렇습니다 잘못된 접근이면 memberService에 접근하기 전에 이미 webSecurity config에서 거릅니다.

2021-09-30 17:30 UTC, powerkim417 commented on src/main/java/com/emotie/api/guestbook/service/GuestbookService.java
> +    }
메서드명 뒤에 By~~ 를 붙여 수정하겠습니다.

2021-09-30 17:31 UTC, powerkim417 commented on src/main/java/com/emotie/api/guestbook/domain/Guestbook.java
> +@Getter
넵 알겠습니다

2021-09-30 17:35 UTC, powerkim417 commented on src/main/java/com/emotie/api/member/domain/Member.java
> +    // TODO: reference object의 경우 one to many로 연결하는게 더 좋다는데..
elementcollection 은 value object 일때 좀 더 적합해 보이고 onetomany는 reference object일때 좀 더 적합해 보인다는 현직자의 코멘트를 듣고 저도 좀 고민해보려고 일단 todo로만 남겼었습니다.

2021-09-30 17:54 UTC, powerkim417 commented on src/main/java/com/emotie/api/member/domain/Member.java
> +    }
넵 수정하겠습니다!

2021-09-30 17:57 UTC, powerkim417 commented on src/main/java/com/emotie/api/member/service/MemberService.java
>                      throw new UnauthenticatedException("로그인하지 않았습니다.");
넵 관련 코드 모두 삭제하겠습니다.

2021-09-30 18:02 UTC, powerkim417 commented on src/main/java/com/emotie/api/guestbook/service/GuestbookService.java
> +        checkGetAllBoardsRequestValidity(user, nickname);
밑에 checkLogin 관련 코멘트를 내려가면서 늦게 봤네요 ㅠㅠ 확인했습니다!

2021-09-30 18:25 UTC, powerkim417 commented on src/main/java/com/emotie/api/guestbook/service/GuestbookService.java
> +        if (!(user.equals(guestbook.getWriter()) || user.equals(guestbook.getOwner()))) {
그러면 말씀해주신 대로 하기 위해 check 메서드에 boolean 반환값을 넣어줘야 할까요?? 다른 코드에선 전부 check 메서드가 예외를 던지고 따로 반환값이 없는 것 같아서 조심스럽게 여쭤봅니다..

2021-09-30 18:26 UTC, powerkim417 commented on src/main/java/com/emotie/api/guestbook/service/GuestbookService.java
> +    }
넵 같이 수정하겠습니다

2021-09-30 18:43 UTC, powerkim417 commented on src/main/java/com/emotie/api/guestbook/service/GuestbookService.java
> +    }
checkWriter류는 멤버/방명록 도메인 어디에 있어도 똑같은데, checkOwner류는 방명록 도메인에서 유저를 인자로 받아오는 것이 훨씬 코드가 간결해서 일관성 있게 두 check 모두 방명록 도메인에 넣겠습니다!

2021-09-30 19:04 UTC, powerkim417 commented on src/main/java/com/emotie/api/guestbook/domain/Guestbook.java
> +@Getter
`public static GuestbookResponse of(Guestbook guestbook) {
        return GuestbookResponse.builder()
                .id(guestbook.getId())
                .ownerId(guestbook.getOwner().getUUID())
                .writerId(guestbook.getWriter().getUUID())
                .content(guestbook.getContent())
                .reportCount(guestbook.getReportCount())
                .createdAt(guestbook.getCreatedAt())
                .updatedAt(guestbook.getUpdateAt())
                .build();
    }`

2021-09-30 22:11 UTC, hcpak commented on src/main/java/com/emotie/api/member/domain/Member.java
> +    // TODO: reference object의 경우 one to many로 연결하는게 더 좋다는데..
혹시 reference object가 뭔지 설명해주실 수 있나요? 그리고 value object에 대해서 언제 쓰이는지 잘 모르겠습니다.

2021-09-30 22:13 UTC, hcpak commented on src/main/java/com/emotie/api/guestbook/service/GuestbookService.java
> +        if (!(user.equals(guestbook.getWriter()) || user.equals(guestbook.getOwner()))) {
boolean 반환값을 넣어줘야할 거 같습니다. 서비스 로직에서 check 메서드가 따로 반환값이 없긴 했지만 상관 없어보여요.

2021-09-30 22:43 UTC, hcpak commented on src/main/java/com/emotie/api/guestbook/domain/Guestbook.java
> +@Getter
아하 이런 문제가 있었군요. 그러면 getter를 반드시 필요한 상황이라 없애면 안될 거 같네요. 다른 방법은 생각이 나지 않네요.

2021-09-30 22:45 UTC, hcpak commented on src/main/java/com/emotie/api/guestbook/controller/GuestbookController.java
> +        guestbooks.sort(Comparator.comparing(GuestbookResponse::getCreatedAt));
제가 아까 이 부분에 대해서 보지 못했는데, dto로 변환해주는 로직과 소팅하는 로직은 서비스단에 있는 것이 좀 더 좋다고 판단되긴 하는데, 솔직히 어떤 게 정답인지는 저도 잘 모르겠습니다. 우리 팀에서 어떻게 할 지 정해볼까요?

2021-09-30 22:46 UTC, hcpak requested changes
pagination 부분은 추가해야 할 거 같아요!

2021-10-01 06:04 UTC, powerkim417 commented on src/main/java/com/emotie/api/guestbook/service/GuestbookService.java
> +        if (!(user.equals(guestbook.getWriter()) || user.equals(guestbook.getOwner()))) {
네 알겠습니다!

2021-10-01 06:08 UTC, powerkim417 commented on src/main/java/com/emotie/api/guestbook/service/GuestbookService.java
> +        if (!(user.equals(guestbook.getWriter()) || user.equals(guestbook.getOwner()))) {
어제 리팩토링을 거치면서 해당 부분을 guestbook 도메인에 넣었더니
`!(this.writer.equals(user) || this.owner.equals(user))`
코드가 위와 같이 수정되면서 get도 필요없고 check메서드를 참조할 필요도 없어졌네요.. ㅎㅎ; boolean 반환 값 없이 이렇게 수정하겠습니다!

2021-10-01 06:09 UTC, powerkim417 commented on src/main/java/com/emotie/api/guestbook/domain/Guestbook.java
> +@Getter
그러면 getter가 필요없는데 무작정 선언했던 부분만 우선 지우겠습니다.

2021-10-01 06:16 UTC, powerkim417 commented on src/main/java/com/emotie/api/member/domain/Member.java
> +    // TODO: reference object의 경우 one to many로 연결하는게 더 좋다는데..
reference object는 각 멤버들이나 방명록들 처럼 시스템 내에서 유일하게 존재해야 하는 객체를 의미합니다.
이 객체들을 비교할 때는 객체 자체가 같은지에 대한 비교(동일성)를 하게 됩니다.
value object는 멤버가 가지고 있는 돈의 수량(10000원, 50000원)이나 나이와 같이 반드시 유일하게 존재할 필요가 없는 그냥 값같은 존재라고 생각하면 될 것 같습니다.
이 객체들을 비교할 때는 값이 동등한 지만 비교하게 되는데(동등성), 지갑 안의 10000원과 계좌의 10000원은 다르지만 둘다 같은 10000원으로 처리하는 것이 그 예시가 될 것 같습니다.

이를 바탕으로 위와 같은 코멘트를 받았는데, 제가 아직 element collection과 one to many의 차이를 잘 모르겠어서 좀 더 고민해보려고 합니다.

2021-10-01 06:19 UTC, powerkim417 commented on src/main/java/com/emotie/api/guestbook/repository/GuestbookRepository.java
> +}
넵 제가 pagination 관련 자료를 찾아보다가 답변을 못드렸네요. pagination 적용하겠습니다! 근데 제가 아직 잘 할줄 몰라서 mincho나 다른 코드를 참고하면서 해보겠습니다.

2021-10-01 06:19 UTC, powerkim417 commented on src/main/java/com/emotie/api/guestbook/service/GuestbookService.java
> +    public List<Guestbook> getAllBoards(Member user, String nickname) {
넵 알겠습니다

2021-10-01 07:16 UTC, powerkim417 commented on src/main/java/com/emotie/api/guestbook/controller/GuestbookController.java
> +        guestbooks.sort(Comparator.comparing(GuestbookResponse::getCreatedAt));
저희끼리 논의한 결과 서비스에 너무 많은 로직이 과포화되지 않는 이상은 부가적인 로직들에 대해 모두 서비스에 구현하는 것으로 정했습니다!

2021-10-01 07:20 UTC, powerkim417 commented on src/main/java/com/emotie/api/guestbook/domain/Guestbook.java
> +@Getter
Response DTO 객체의 경우 @Getter를 직접 사용하진 않는데, 빼니까 500 에러랑 406 에러가 발생하네요.. 도메인 클래스에서 사용하지 않는 @Getter만 일단 삭제했습니다.

2021-10-02 03:33 UTC, hcpak commented on src/main/java/com/emotie/api/guestbook/domain/Guestbook.java
> +@Getter
수고하셨습니다!

2021-10-02 03:33 UTC, hcpak commented on src/main/java/com/emotie/api/guestbook/service/GuestbookService.java
> +        if (!(user.equals(guestbook.getWriter()) || user.equals(guestbook.getOwner()))) {
수고하셨습니다!

2021-10-02 03:35 UTC, hcpak commented on src/main/java/com/emotie/api/guestbook/service/GuestbookService.java
> +        return guestbookRepository.findForUserByOwner(owner, Guestbook.reportCountThreshold);
그런 것도 방법 중 하나겠네요. 저런 if 조건문 분기는 뭔가 예쁘지 않다고 느껴져서... ㅎㅎ 이건 저만의 견해이긴 합니다.

2021-10-02 03:35 UTC, hcpak commented on src/main/java/com/emotie/api/guestbook/service/GuestbookService.java
> +    }
넵넵 그것이 훨씬 더 좋을 거 같습니다!

2021-10-02 03:38 UTC, hcpak commented on src/main/java/com/emotie/api/member/domain/Member.java
> +    // TODO: reference object의 경우 one to many로 연결하는게 더 좋다는데..
아하 그렇군요. reference object이니 oneToMany 방식으로 동작하는 게 나아보이네요. 근데 reference object일 때 element collection하면 어떻게 될지 궁금하긴 하네요.

2021-10-02 03:38 UTC, hcpak commented on src/main/java/com/emotie/api/guestbook/controller/GuestbookController.java
> +        guestbooks.sort(Comparator.comparing(GuestbookResponse::getCreatedAt));
넵넵 좋습니다!

2021-10-02 18:46 UTC, powerkim417 commented on src/main/java/com/emotie/api/guestbook/service/GuestbookService.java
> +        return guestbookRepository.findForUserByOwner(owner, Guestbook.reportCountThreshold);
두 쿼리가 조건 딱 하나 차이라 좀 더 깔끔하게 짤 수 있을것 같은데.. 좀 더 찾아봐야겠네요 ㅠㅠ

2021-10-05 13:39 UTC, Bucket1572 reviewed
고생하셨습니다! 제가 남긴 리뷰는 그리 중요한 내용은 아니고, 저도 불확실한 내용입니다;; 다만, 한 번 origin을 **fetch 해 오거나 pull 해 올 필요**는 있어 보입니다.

2021-10-05 13:39 UTC, Bucket1572 commented on src/main/java/com/emotie/api/diaries/domain/Diaries.java
>  @Getter
다이어리 같은 경우에는 상당 부분 바뀌어서, 지금 origin에 merge 된 상태를 pull 하셔야 할 것 같습니다.

2021-10-05 13:39 UTC, Bucket1572 commented on src/main/java/com/emotie/api/guestbook/controller/GuestbookController.java
> +        // TODO: 이 부분을 여기 둘지 서비스단에 옮길지 논의
제가 잘 몰라서 그러기는 하는데, 이 부분은 service 안에서 처리하는 게 낫지 않을까요?

2021-10-06 09:07 UTC, powerkim417 commented on src/main/java/com/emotie/api/guestbook/controller/GuestbookController.java
> +        // TODO: 이 부분을 여기 둘지 서비스단에 옮길지 논의
넵 맞습니다. 그래서 이후 commit에서
service와 controller가 엔티티가 아닌 DTO를 주고받도록 수정하였습니다.

2021-10-08 08:55 UTC, Bucket1572 commented on src/main/java/com/emotie/api/guestbook/controller/GuestbookController.java
> +        // TODO: 이 부분을 여기 둘지 서비스단에 옮길지 논의
오늘 회의로 이 내용은 결정된 것 같습니다. 이 대화는 resolve 하겠습니다.

2021-10-13 11:35 UTC, hcpak approved these changes
페이지네이션까지 구현 완료하셨네요! 정말 수고 많이하셨습니다!

2021-10-28 14:14 UTC, merged